var helpList = {
  '3': 'What are the system requirements to run Dropbox?',
  '4': 'How do I sync files between computers?',
  '5': 'Is there a limit or maximum to how big my files can be?',
  '6': 'What types of files can I store or view on Dropbox?',
  '7': 'Where does Dropbox store everyone\'s data?',
  '8': 'Does Dropbox always upload/download the entire file any time a change is made?',
  '9': 'In what order does Dropbox sync files?',
  '10': 'Will files I put in Dropbox be synced across other machines even if they\'re offline?',
  '11': 'How do I recover previous versions of my file?',
  '12': 'Can I have Dropbox sync files outside my Dropbox folder?',
  '13': 'How do I upgrade to the latest version of the Dropbox application?',
  '14': 'How much space does my Dropbox account have left?',
  '15': 'Can I earn more space on my Dropbox account?',
  '16': 'What is the Public folder for?',
  '18': 'What is the Photos folder for?',
  '19': 'How do I share folders with other people?',
  '20': 'Can I share files with non-Dropbox users?',
  '21': 'Does Dropbox support connecting through a proxy server?',
  '22': 'How do I get Dropbox to work on my corporate network?',
  '23': 'Do I need to configure my firewall to work with Dropbox?',
  '25': 'How do I unlink or relink a computer, phone, or tablet from my account?',
  '26': 'How do I make Dropbox sync faster or control the bandwidth used?',
  '27': 'How secure is Dropbox?',
  '28': 'Can I specify my own private key for my Dropbox?',
  '30': 'Is Dropbox down?',
  '31': 'Do you have Dropbox in my language?',
  '32': 'Can I access Dropbox on my mobile device?',
  '34': 'How do I get notified of changes in my Dropbox?',
  '36': 'What\'s a conflicted copy?',
  '37': 'How do I change my password?',
  '38': 'How much longer until Dropbox is finished uploading/syncing?',
  '39': 'How many files can I store in my Dropbox?',
  '40': 'How do I delete files from Dropbox on my computer?',
  '41': 'How do I uninstall Dropbox?',
  '42': 'Can I host Dropbox on my server?',
  '43': 'How do I delete my account?',
  '44': 'My Dropbox has an "x" on it. What\'s wrong?',
  '45': 'Why did my shared link stop working?',
  '46': 'Can I have an invoice for my Dropbox subscription?',
  '48': 'What is Growl? How does Dropbox use it?',
  '49': 'Can I download entire folders on the Dropbox website?',
  '51': 'Do you accept PayPal?',
  '52': 'Dropbox says my file is in use. What\'s wrong?',
  '54': 'How do I earn bonus space for referring friends to Dropbox?',
  '55': 'Where can I find the status of the invitations I\'ve sent out for referrals?',
  '56': 'What do each of the referral statuses mean?',
  '57': 'Will I still get credit if my friend signs up using a different email address?',
  '59': 'Will joining someone else\'s shared folder use my quota?',
  '60': 'Can I set file permissions for members of my shared folders?',
  '61': 'Can I have two Dropbox accounts on the same computer or device?',
  '62': 'Do you offer WebDAV, Email Attachments, or FTP support?',
  '63': 'How do I change my account settings?',
  '64': 'Can I rename or move a shared folder?',
  '65': 'What is the Dropbox desktop application (client)?',
  '71': 'What are .lnk files?',
  '72': 'What do I do if Dropbox is stuck syncing, won\'t launch, or reports an error?',
  '73': 'How much does Dropbox cost?',
  '74': 'What are the system requirements for the Dropbox mobile app?',
  '76': 'Does my existing Dropbox account work with my phone or tablet?',
  '80': 'What kinds of files and documents are viewable on my phone or tablet?',
  '81': 'How do I remove files from my mobile device?',
  '82': 'How does syncing work?',
  '83': 'Will movies and audio files play on my phone or tablet?',
  '84': 'How do I upload files from my phone or tablet?',
  '87': 'How do I save files for offline viewing on my mobile device?',
  '88': 'How much can I store on my mobile device?',
  '89': 'How do I move my Dropbox folder to a new location?',
  '90': 'How do I add or upload files to my Dropbox?',
  '108': 'Do you offer a reseller program?',
  '113': 'What is Extended Version History?',
  '114': 'How do I opt out of Dropbox email newsletters and tips?',
  '115': 'What happens when I delete a file?',
  '122': 'Does Dropbox keep backups of my files?',
  '137': 'What is LAN sync?',
  '140': 'How can I tell if a file or folder is shared or private?',
  '141': 'What is a system tray or menu bar?',
  '142': 'What if Dropbox can\'t fit my hard drive? Can I select which files to sync?',
  '144': 'Why is Dropbox using so much RAM?',
  '145': 'Why aren\'t certain files on one computer syncing to another?',
  '146': 'How do I know when Dropbox is syncing?',
  '149': 'How do I rejoin a shared folder?',
  '150': 'Why did my payment fail?',
  '152': 'Why do files move instead of copy?',
  '154': 'Why aren\'t my Dropbox icon overlays appearing correctly?',
  '156': 'How do I unshare a shared folder?',
  '157': 'Security Overview',
  '158': 'How do I cancel my subscription and return to a free Dropbox Basic account?',
  '159': 'Why can\'t I establish a secure connection?',
  '160': 'Can I buy more than 1 TB of space?',
  '161': 'Why does my bank statement show multiple charges for one upgrade?',
  '163': 'How do I leave a shared folder?',
  '164': 'I have plenty of storage space available. Why does Dropbox say I have low disk space?',
  '166': 'How do I find and change my desktop application preferences?',
  '167': 'How do I link to a file or folder?',
  '168': 'I forgot my password. How do I reset it?',
  '175': 'How do I save space on my computer with Selective Sync?',
  '180': 'How do I pause and resume syncing from Dropbox?',
  '193': 'How do I resolve issues with my Android installation?',
  '200': 'How much free referral space can I earn?',
  '201': 'How do I force a file to download from the web?',
  '202': 'How do I change my email address?',
  '203': 'Why does Dropbox require Mac Keychain access?',
  '207': 'What are keyboard shortcuts and how do I use them?',
  '209': 'Why does the Dropbox iOS app need my location data?',
  '210': 'What is Dropbox\'s copyright policy?',
  '211': 'Can I convert my existing account to Dropbox Business?',
  '212': 'How do I view the amount of licenses and space left on our Business account?',
  '213': '4 Steps to set up Dropbox Business',
  '214': 'How do I delete a member from my Dropbox Business team?',
  '215': 'Is there a limit to the number of computers I can link to my account?',
  '216': 'Do past revisions of my files count against my storage quota?',
  '217': 'What domains does Dropbox use in an official capacity?',
  '218': 'Will everyone on my team have access to my files?',
  '224': 'How are shared folders different with Dropbox Business?',
  '225': 'How do I add licenses or space to my Dropbox Business account?',
  '227': 'How do I set a four-digit passcode on my phone or tablet?',
  '228': 'What kinds of files can I view on my mobile device?',
  '230': 'How do I delete files?',
  '231': 'How do I play videos?',
  '232': 'How do I upload files?',
  '233': 'How do I share a file?',
  '234': 'How much can I store?',
  '235': 'Why does the Dropbox iOS app need location data?',
  '236': 'How do I set a four-digit passcode?',
  '238': 'Which standards and regulations does Dropbox Business comply with?',
  '240': 'Why do the pictures I download from Dropbox appear in Google Plus?',
  '241': 'Can I see the billing information of other administrators on my Dropbox Business account?',
  '242': 'How do I change the owner of a shared folder?',
  '243': 'How do I install Dropbox?',
  '246': 'How do I add or remove Dropbox from my Linux repository?',
  '247': 'How do I build the Dropbox installer for Linux from source?',
  '248': 'What\'s a white space conflict?',
  '249': 'Is my HTC device eligible for the special promotion?',
  '250': 'How do I link or unlink my Facebook or Twitter account?',
  '251': 'What information does Dropbox and Facebook exchange when I link my accounts?',
  '267': 'How can I access my files offline?',
  '271': 'Dropbox can\'t access your Windows Registry',
  '272': 'Dropbox can\'t access your Windows Registry',
  '274': 'How do I share a file or folder with others?',
  '275': 'How can I get more space?',
  '276': 'Why do I get an error when permanently deleting files?',
  '288': 'Where are my Camera Uploads?',
  '289': 'How do I use Camera Upload?',
  '295': 'How do I complete the Dropbox Get Started steps to claim my promotional space?',
  '296': 'How do I recover deleted files?',
  '297': 'Is my Samsung device eligible for the Dropbox space promotion?',
  '300': 'A little something...for you!',
  '307': 'How do I enable or disable Camera Upload?',
  '313': 'How do I rename a file or folder?',
  '314': 'How do I remove a member from a shared folder?',
  '315': 'How do I select multiple files on the website?',
  '316': 'Please install Dropbox to import photos',
  '317': 'How do I verify my email address?',
  '319': 'How do I sort by file name, kind, extension, size, or modified date on the website?',
  '321': 'Where is my Dropbox folder?',
  '328': 'What is the Dropbox cache folder?',
  '331': 'Where is my free space?',
  '333': 'What happens if my paid account or promotion expires?',
  '334': 'How do I remove a link to a file or folder?',
  '346': 'How do I reinstall the Dropbox iOS app?',
  '359': 'How do I keep others from inviting people to my shared folder?',
  '360': 'Who is the owner of a shared folder?',
  '362': 'How can I use Active Directory to manage Dropbox Business members?',
  '363': 'How do I enable two-step verification on my account?',
  '364': 'What do I do if I lost my phone or can\'t sign in using two-step verification?',
  '365': 'How do I choose a secure password for Dropbox?',
  '367': 'How do I change my phone number for two-step verification?',
  '370': 'What do I do if the Dropbox iOS app crashes?',
  '379': 'Why did my password expire?',
  '383': 'How do I add a file to my Facebook group?',
  '389': 'How do I move files between my two Dropboxes?',
  '390': 'What\'s the Dropbox Space Race?',
  '391': 'Dropbox Space Race FAQ',
  '392': 'What happens to my Pro subscription on a Dropbox Business trial?',
  '400': 'How do I select an event to recover deleted files from?',
  '403': 'Do I need a Dropbox account to join a shared folder?',
  '406': 'What do the icons on my files mean?',
  '419': 'How do I use Camera Upload?',
  '422': 'Dropbox Business Resources',
  '429': 'How do I switch between my personal and work accounts?',
  '430': 'How does syncing work on my mobile device?',
  '485': 'How do I use photo albums on my Android device?',
  '486': 'How do I share photos from my Android device?',
  '487': 'Why does my video get cut off when other people view it?',
  '488': 'Can I access the Dropbox account of someone who has passed away?',
  '492': 'The Dropbox photos page—all of your photos and videos in one place.',
  '493': 'How do I create a photo album?',
  '494': 'How do I add photos to an album?',
  '495': 'How do I remove photos from an album?',
  '496': 'How do I rename a photo album?',
  '497': 'How do I delete a photo album?',
  '498': 'How do I share photos with other people?',
  '499': 'How do I unshare links to photos?',
  '500': 'What is background uploading?',
  '501': 'How do I sort my files?',
  '504': 'How do I administer sharing for my team?',
  '505': 'How can I get an audit of my Business account\'s activity?',
  '506': 'Why can\'t I share stuff with people outside my business account?',
  '508': 'What happens if my work account is deleted from a Dropbox Business team?',
  '526': 'How do I join a shared folder I\'ve been invited to?',
  '531': 'How do I cancel my Dropbox Business trial?',
  '532': 'How do I cancel Dropbox Business and get a refund for my subscription?',
  '967': 'Why do I see activity from Dropbox Support on my Business account\'s Activity page?',
  '969': 'My files are missing. How do I get them back?',
  '970': 'How do I find a deleted or missing file in my Dropbox account?',
  '971': 'What\'s the VAT number for Dropbox, and how can I add a VAT ID to my account?',
  '972': 'Where can I get a copy of Dropbox\'s W-9 form?',
  '973': 'How do I use Dropbox with Yahoo Mail?',
  '974': 'Will my Dropbox Business subscription renew automatically?',
  '986': 'How do I create a team folder for my Business account?',
  '1009': 'How do I make someone on my Business account an admin?',
  '1010': 'How do I view my Business account\'s billing history?',
  '1011': 'How do I change the name of my Business account?',
  '1012': 'When does my Dropbox Business subscription renew?',
  '1366': 'Does Dropbox use any open source software?',
  '1908': 'How do I change my Dropbox Business billing information?',
  '1909': 'How do I set up single sign-on (SSO) for my Business account?',
  '1921': 'Frequently asked questions about single sign-on (SSO) for Dropbox Business administrators',
  '1925': 'Single sign-on (SSO) was turned on for our Business account. What do I need to do?',
  '1926': 'I\'m a Dropbox Business user. Why can\'t I sign in?',
  '1931': 'Can I share a folder that\'s in another shared folder?',
  '1938': 'Yes, that was me',
  '1939': 'No, I don\'t think I signed in from a new location',
  '1940': 'How do I find and change my desktop application preferences?',
  '1941': 'How do I move my Dropbox to a new computer?',
  '1942': 'How do I update my Dropbox Pro billing information?',
  '1944': 'How do I rejoin a team folder that I\'ve left or deleted?',
  '1946': 'What is a Selective Sync conflict?',
  '1963': 'How do I copy my photos from iPhoto to Dropbox?',
  '1964': 'How do I share and save screenshots with Dropbox?',
  '1968': 'How does the Dropbox service work?',
  '1970': 'Why don\'t my gallery links work anymore?',
  '1972': 'I think my account was compromised. What do I do?',
  '1973': 'How can I protect my Dropbox account?',
  '1975': 'How do I copy my photos from iPhoto to Dropbox?',
  '1976': 'What happened to Votebox?',
  '1977': 'Why aren\'t my photos appearing on the Photos page?',
  '1978': 'Why aren\'t my photos appearing in the mobile app?',
  '1979': 'Why does the Dropbox Android app request access to my contacts?',
  '1980': 'Why does Dropbox for Android need access to my camera?',
  '1983': 'How do I change the way dates are shown on the website?',
  '4200': 'Is my Dell device eligible for the Dropbox space promotion?',
  '4204': 'Why were my shared links or file requests banned?',
  '4206': 'How do I use remote wipe to delete the Dropbox folder from a member’s device?',
  '4207': 'How does the multi-account feature affect Dropbox folder paths?',
  '4208': 'Why did Dropbox change the names of my photos?',
  '4210': 'Why did the name of my work Dropbox change?',
  '4211': 'What does "OperationalError" or "BrokenTempDirError" mean?',
  '4212': 'Can I sign out of just one app?',
  '4213': 'How does Dropbox use cookies and other similar technologies?',
  '4223': 'Why haven’t I received my promotion space?',
  '4224': 'How do I disable or enable the public folder for members of my Dropbox Business team?',
  '4226': 'How can I keep track of sharing activity in Dropbox Business?',
  '4227': 'Remote wipe overview',
  '4228': 'Account transfer overview',
  '4229': 'What happens when my HTC, Samsung, or Sony promotion expires?',
  '4233': 'Step 1: Invite new members',
  '4234': 'Step 2: Install Dropbox',
  '4235': 'What happens when I connect a personal and work Dropbox on my devices?',
  '4236': 'How do I allow only one Dropbox per computer?',
  '4237': 'How do photos work in Dropbox Business?',
  '4238': 'How do I sign in to a personal and work Dropbox on my devices?',
  '4241': 'What does it look like to have two Dropboxes on my devices?',
  '4242': 'Can I use Carousel or Mailbox with Dropbox Business?',
  '4245': 'Step 3: Add your files',
  '4246': 'Step 4: Share your folders',
  '4247': 'Step 5: Manage your team',
  '4248': 'How do I use remote wipe when deleting a team member\'s account?',
  '4249': 'Does connecting my Dropbox accounts give an admin visibility into my personal account?',
  '4250': 'How do I delete the Dropbox folder from a lost or stolen device?',
  '4251': 'How do I track the remote wipe status of my device?',
  '4252': 'How do I transfer a former team member\'s files to another member?',
  '4253': 'What exactly gets transferred when I use account transfer?',
  '4254': 'How can I keep track of my account transfer activity?',
  '4255': 'What will account transfer look like for the recipient?',
  '4270': 'How do I connect or disconnect a personal Dropbox from a Dropbox Business account?',
  '4399': 'I think I\'ve found a Dropbox security bug or vulnerability. How do I report it?',
  '4427': 'What if I have more than 10 accounts?',
  '4429': 'Welcome to Dropbox Business',
  '4448': 'Can I use a Dropbox Business account with Mailbox?',
  '4449': 'How can I customize security in Dropbox Business?',
  '4450': 'What\'s the best way to offboard Dropbox Business team members?',
  '4452': 'How do I get extra space for connecting a personal and work Dropbox account?',
  '4453': 'Get Started with Dropbox Business',
  '4454': 'Download the Dropbox desktop application',
  '4455': 'Add files to your Dropbox',
  '4456': 'Use Selective Sync on your desktop',
  '4457': 'Start sharing with Dropbox',
  '4458': 'Dropbox Business admin guide',
  '4459': 'Different ways to share',
  '4460': 'Two-step verification: An extra layer of security',
  '4461': 'Contact Dropbox support',
  '4495': 'What control does my admin have over my work Dropbox?',
  '4574': 'How do I join Dropbox Business?',
  '4576': 'How do I join Dropbox Business as a new user?',
  '4577': 'How do I migrate an existing Dropbox Basic or Pro account to Dropbox Business?',
  '4578': 'If I’m already on Dropbox Business, how do I connect a personal and a work Dropbox?',
  '4579': 'What does it look like to connect a personal and a work Dropbox through my mobile device?',
  '4584': 'How can I programmatically find the Dropbox folder paths?',
  '4623': 'How do I move files between my work and personal Dropbox accounts?',
  '5046': 'Signatures',
  '5048': 'Is Mailbox like artificial intelligence?',
  '5050': 'How do I re-create a shared link that was broken?',
  '5065': 'How do I get Dropbox crash logs from my iPhone or iPad?',
  '5066': 'How can I add photos from MyFamily to Carousel?',
  '5067': 'Yes, that was me',
  '5069': 'What do I do if Dropbox says my email is already taken?',
  '5084': 'Why can\'t I delete that photo?',
  '5089': 'How do I cancel my Pro subscription and return to a free Dropbox Basic account?',
  '5090': 'How do I upgrade to a Dropbox Pro subscription?',
  '5091': 'I already have a Pro plan. How do I downgrade or switch from an annual or monthly plan?',
  '5092': 'How do I cancel automatic renewals for my Dropbox Pro subscription?',
  '5093': 'What if I upgraded the wrong account, or want to transfer my Pro storage to another account?',
  '5094': 'Why did PayPal send me an email saying it canceled my automatically renewing subscription?',
  '5096': 'Can Dropbox change my invoice information?',
  '5097': 'Can I change the date I\'m billed for my subscription renewal?',
  '5098': 'Upgrading to Dropbox Pro from the Apple App Store or Google Play Store',
  '5101': 'Can I subscribe for more than one year and pay in advance?',
  '5102': 'Can I gift a Dropbox Pro subscription?',
  '5103': 'I paid for a Pro subscription but didn\'t receive the updated space. How can I access my storage?',
  '5105': 'What happens to my existing storage quota when I purchase a Pro subscription?',
  '5821': 'Can I change the currency on my Dropbox Pro or Dropbox Business subscription?',
  '5823': 'Shared folder permissions',
  '5825': 'How do I sign up my team for early access to Dropbox Business features?',
  '5886': 'Shared links controls overview',
  '5887': 'How can I limit access to a shared link?',
  '5888': 'How can I set an expiration for a shared link?',
  '6229': 'Yes, that was me',
  '6230': 'No, I don\'t think that was me',
  '6231': 'What information can a third-party app access when I link it to my account?',
  '6232': 'How do I unlock or change view-only permissions for a copy of a shared folder?',
  '6239': 'How is Dropbox Pro changing?',
  '6242': 'How do I star an email in Mailbox?',
  '6251': 'Why is Dropbox displaying a message saying I’m running an old version of the application?',
  '6252': 'Why did I get an email saying I’m running an old version of the application?',
  '6269': 'Why can’t I install the new version of Dropbox on my Mac?',
  '6271': 'What roles and permissions can members of a shared folder have?',
  '6272': 'How do I set view-only permissions for members of a shared folder?',
  '6273': 'How do I control who can assign roles and permissions in a shared folder?',
  '6274': 'Shared folder permissions and Dropbox Business team-wide sharing options',
  '6275': 'What does it look like when someone with view-only permissions tries to edit a file?',
  '6587': 'How does the new Dropbox Business space work?',
  '6590': 'I\'m part of the beta! Where do I submit feedback?',
  '6634': 'How do I connect Dropbox to AD FS 2.0 for single sign-on (SSO)?',
  '6635': 'How can I use full-text search to search the contents of my files?',
  '6636': 'How do I control who accesses links created from my shared folders?',
  '6637': 'Is my HP device eligible for the Dropbox space promotion?',
  '6640': 'Is my Samsung device an affected device, unable to redeem promotional space?',
  '6642': 'What is Dropbox?',
  '6691': 'Package files and Dropbox',
  '6711': 'How do I cancel a trial of Dropbox Pro?',
  '6712': 'Dropbox Business admin dashboard overview',
  '6713': 'How do I resend pending invites for my Dropbox Business team?',
  '6714': 'How do I see my Dropbox Business team members’ activity over time?',
  '6715': 'What can I search for in the search bar of the Dropbox Business admin dashboard?',
  '6860': 'Is my Acer device eligible for the Dropbox space promotion?',
  '6862': 'Dropbox for Salesforce: How do I share the Salesforce Documents folder?',
  '6863': 'Dropbox for Salesforce: How do I add to standard objects?',
  '6864': 'Dropbox for Salesforce: How do I install Dropbox for Salesforce?',
  '6865': 'Dropbox for Salesforce: How do I add files?',
  '6866': 'Dropbox for Salesforce: How do I enable automatic renaming?',
  '6867': 'Dropbox for Salesforce: How do I set up security?',
  '6868': 'Dropbox for Salesforce: How can I automatically create a subfolder structure?',
  '6869': 'Dropbox for Salesforce: How do I grant only my team access?',
  '6870': 'Dropbox for Salesforce: What are the .sfdb files in my Dropbox?',
  '6871': 'Dropbox for Salesforce: How do I view or download a file?',
  '6872': 'Dropbox for Salesforce: How can I share a file or folder to Chatter?',
  '6873': 'Dropbox for Salesforce: How do I enable Dropbox for Salesforce on Salesforce1 Mobile?',
  '6874': 'Dropbox for Salesforce: Frequently Asked Questions',
  '6875': 'Dropbox for Salesforce: How do I grant access to Salesforce users?',
  '6876': 'Can I manage a conversation?',
  '6877': 'Dropbox for Salesforce: How do I make my own folder name structure?',
  '6878': 'Dropbox for Salesforce: How do I uninstall Dropbox for Salesforce?',
  '6879': 'Dropbox for Salesforce: What is a Salesforce Object API name?',
  '6880': 'Dropbox for Salesforce: How do I create a Dropbox folder in Salesforce?',
  '6881': 'Dropbox for Salesforce: How do I delete or restore Dropbox files in Salesforce?',
  '6882': 'Dropbox for Salesforce: How do I work with custom objects?',
  '6885': 'Can I purchase Dropbox via SEPA Direct Debit?',
  '6886': 'How can I set a default language for my Dropbox Business team?',
  '6887': 'iCloud Photo Library (Beta) issue in iOS 8.1',
  '6908': 'What is Dropbox Pro?',
  '6910': 'Dropbox for Salesforce: Resources and Links',
  '6955': 'Why does the blue Dropbox icon look different?',
  '6957': 'Why did a shared link take me directly to my Dropbox?',
  '6999': 'How do I edit Microsoft Office files stored in my Dropbox from my mobile device?',
  '7037': 'Microsoft Office for Dropbox—frequently asked questions',
  '7038': 'Why aren\'t the Dropbox files I\'ve edited in the Office apps refreshing properly on iOS?',
  '7040': 'Is my Sony device eligible for the Dropbox space promotion?',
  '7041': 'How do I manage my Dropbox Business team’s shared links?',
  '7042': 'Why does the Carousel full-screen mode look different?',
  '7144': 'Why is Finder integration disabled in Yosemite OS X 10.10.0?',
  '7180': 'I need a new quote for my Dropbox Business team',
  '7183': 'The Dropbox Finder integration and issues with Apple\'s OS X Yosemite: FAQs',
  '7185': 'How do I leave a group?',
  '7223': 'How do I delete a group?',
  '7224': 'How do I transfer ownership of or add an owner to a group?',
  '7225': 'How do I change the name of a group?',
  '7226': 'How do I share with a group?',
  '7227': 'How do I remove members from a group?',
  '7228': 'How do I add members to a group?',
  '7229': 'How do I create a group?',
  '7230': 'How do I view and manage the groups in my Dropbox Business team?',
  '7231': 'Can I control who can create groups?',
  '7232': 'What are groups?',
  '7238': 'How do I remove user licenses when renewing my Dropbox Business account?',
  '7474': 'What is the Dropbox Business API, and what apps are available for my team?',
  '7475': 'Can I create albums on Carousel?',
  '7476': 'Can I share my photos to other applications, like WhatsApp and Instagram?',
  '7477': 'On which platforms and devices can I use Carousel?',
  '7523': 'Can Carousel help me free up space on my phone?',
  '7670': 'How do I use the Dropbox badge to collaborate?',
  '7671': 'How do I redeem the Dropbox promotion that comes with my device?',
  '7672': 'What is the Dropbox badge?',
  '7673': 'How do I set a profile picture?',
  '7674': 'Why am I getting conflicted copies while using the Dropbox badge?',
  '7676': 'Why don’t I see the Dropbox badge?',
  '7677': 'How can I share a link to my file using the Dropbox badge?',
  '7678': 'How can I view file history and revisions using the Dropbox badge?',
  '7679': 'How can I manage my shared folder settings from the Dropbox badge?',
  '7681': 'How can I get the latest version of a file using the Dropbox badge?',
  '7683': 'What’s the difference between a conflicted copy and my version of a file?',
  '7689': 'How do I receive and open shared links?',
  '7691': 'How do groups affect sharing permissions?',
  '7692': 'Why did a shared folder become unshared?',
  '7693': 'How can I check that a shared folder is syncing?',
  '7713': 'How do I turn off the Dropbox badge?',
  '8046': 'What is the Carousel shortcut?',
  '8049': 'What is the iPhoto importer, and what do I do if I\'m seeing an error message?',
  '8058': 'Dropbox is ending support for OS X Tiger 10.4 and OS X Leopard 10.5 - why, and what can I do?',
  '8108': 'How do I reinstall the Dropbox app on my Windows Phone or tablet?',
  '8109': 'Why did Dropbox fail to install, and what can I do to complete the installation?',
  '8121': 'What is the Samsung DocumentSync folder, and how can I disable it?',
  '8243': 'How do I get Mailbox crash logs from my iPhone or iPad?',
  '8257': 'Badge Count',
  '8269': 'Notifications',
  '8270': 'Default Browser Settings',
  '8271': 'Why can\'t I swipe to delete directly from a conversation or from the settings screen?',
  '8276': 'Lists',
  '8338': 'How do I remove contacts from other devices or apps from my Dropbox?',
  '8366': 'Default Account',
  '8367': 'I have a question about aliases. Help!',
  '8368': 'What are the Dropbox rules and terms of service?',
  '8391': 'Can I use Dropbox for my organization?',
  '8392': 'Can children use Dropbox?',
  '8393': 'Does Dropbox own my stuff?',
  '8402': 'How do I create a Dropbox account?',
  '8404': 'How do I log in or out of the Dropbox website?',
  '8405': 'I\'m not prompted to enter my two-step verification code when I sign in—why not?',
  '8406': 'How does Dropbox handle viruses or malware?',
  '8408': 'My files were corrupted by ransomware. What can I do?',
  '8409': 'Can I use the Dropbox logo in my promotions?',
  '8411': 'Who can see my files?',
  '8412': 'Do you sell my information to advertisers or third parties?',
  '8413': 'An unknown person shared a file with me. What should I do?',
  '8414': 'I got a notification that my password changed, but I didn\'t initiate this. How can I protect my account?',
  '8415': 'I got an email change notification, but I didn\'t change the email on my Dropbox account. What do I do?',
  '8416': 'I got an SMS code for two-step verification, but I wasn\'t trying to sign in. What do I do?',
  '8417': 'What are the keyboard shortcuts for Mailbox for Mac?',
  '8418': 'Someone else\'s photos are appearing in my Dropbox. Why is this happening?',
  '8419': 'An unknown device is linked to my account. What can I do to protect my account?',
  '8420': 'When does Dropbox turn over information for a legal request?',
  '8423': 'How long does Dropbox keep my deleted files and information?',
  '8571': 'What is the Open button and how does it work?',
  '8572': 'Why don\'t I see the Open button?',
  '8573': 'How do I snooze to desktop/mobile?',
  '8574': 'Can I use Auto-swipe to temporarily pause inbound email?',
  '8785': 'How can I see a file\'s size on the Dropbox website?',
  '8807': 'What is Dropbox for Gmail, and how do I use it?',
  '8836': 'Frequently asked questions about Auto-Swipe',
  '8837': 'My files aren\'t syncing or are slow to sync—what happened and why?',
  '8838': 'My files aren’t syncing or are slow to sync—what happened and why?',
  '8839': 'What is syncing and how does it work?',
  '8840': 'My files are different or stopped updating—what\'s going on?',
  '8842': 'I\'m having trouble authorizing my iCloud account! What\'s going on?',
  '8894': 'My credit card or PayPal payment failed—how can I fix this?',
  '8895': 'My credit card or PayPal payment failed—what happened and why?',
  '8897': 'My credit card or PayPal payment failed—what happened and why?',
  '8904': 'How can I use a license key to claim a Dropbox Pro promotional offer?',
  '8909': 'What is Flashback, and how do I use it?',
  '8920': 'Mailbox isn\'t working properly. What do I do?',
  '8921': 'How do I review and remove admins on my Dropbox Business account?',
  '9006': 'I\'m missing space on my Dropbox Business account—what happened?',
  '9009': 'How do I connect Dropbox and Mailbox?',
  '9010': 'I can\'t share a folder or join someone else\'s shared folder—why?',
  '9016': 'How do Comments work?',
  '9017': 'I\'m over my storage limit—what happens, and what should I do?',
  '9019': 'Is my Lenovo computer eligible for the Dropbox space promotion?',
  '9020': 'Can Carousel help me free up space from my SD card?',
  '9022': 'How can I access my personal information?',
  '9023': 'What happens when I close my account?',
  '9024': 'Does Dropbox use third-party service providers?',
  '9025': 'How do I exclude folders from Carousel?',
  '9026': 'What happens to my promotional space when I connect a Dropbox for Business account?',
  '9027': 'What happens if a credit card payment fails on my Dropbox Business account?',
  '9028': 'Can I have fewer than 5 team members on a Dropbox Business account?',
  '9029': 'How can I switch the email addresses between my personal and work accounts?',
  '9030': 'Are there discounted Dropbox Business subscriptions?',
  '9031': 'What is the hidden "Dropbox" folder on my Windows computer?',
  '9032': 'Why would a Dropbox for Business team member invite be "invalid"?',
  '9033': 'How do I change from monthly to annual billing on my Dropbox Business account?',
  '9034': 'I upgraded to Dropbox for Business—why is my personal account out of space?',
  '9035': 'Can I share a Dropbox account with someone else?',
  '9036': 'How can I stop Dropbox photos from appearing in my Carousel?',
  '9039': 'What is the Samsung Device app, and how does it work with Dropbox?',
  '9040': 'How can I export to an SD card from my Android phone?',
  '9041': 'Some common fixes for the Dropbox Android app',
  '9042': 'Can I delete Dropbox if it came pre-loaded on my Android device?',
  '9043': 'What are "early release" versions of the Dropbox app, and how do I install them?',
  '9044': 'How do I install the Dropbox app on my Kindle?',
  '9045': 'What happened to the edits I made to photos on my iPhone or iPad?',
  '9046': 'How do I enable Touch ID for the Dropbox mobile app on iOS devices?',
  '9047': 'Can I print directly from the Dropbox iOS app?',
  '9048': 'Am I eligible for the Vodafone + Dropbox space promotion (25 GB for new users)?',
  '9049': 'What are suggested members?',
  '9050': 'I can\'t find the Dropbox app on my iOS device—what happened?',
  '9051': 'What is the "Link a Computer" feature, and how do I use it on my iOS device?',
  '9052': 'What payment options are available for Dropbox subscriptions?',
  '9053': 'How do I use Recents?',
  '9054': 'How can I find out the email address for my Dropbox account?',
  '9055': 'How do I connect Dropbox to AD FS 3.0 for single sign-on (SSO)?',
  '9056': 'What are Dropbox Business tiered admins, and how do they work?',
  '9057': 'Battery',
  '9058': 'Am I eligible for the WPS Office + Dropbox space promotion?',
  '9059': 'Bonus Space',
  '9060': 'Sign in with Dropbox',
  '9062': 'Dropbox for Salesforce: how do I make custom objects available for Salesforce1 Mobile?',
  '9063': 'The Dropbox Terms of Service change—what is it, and what does it mean for me?',
  '9064': 'Why am I seeing U.S. sales tax on my Dropbox subscription?',
  '9066': 'What is required two-step verification, and how do I set it up for my Dropbox Business team?',
  '9067': 'How do we migrate a Dropbox Basic or Pro account to Dropbox Business?',
  '9069': 'Will I receive a refund if I cancel my Dropbox Pro subscription?',
  '9077': 'Why don\'t I see the Dropbox sync icons on my files or folders?',
  '9078': 'What will change if I merge my Dropbox Business team with another team?',
  '9080': 'I received an email about an inactive Dropbox account—what do I need to do?',
  '9081': 'What is the Active Directory Connector, and how can I use it for user provisioning?',
  '9082': 'How do I change the name, email, or password on my Dropbox account?',
  '9090': 'What\'s a file request and how do I create one?',
  '9091': 'What\'s a file request and why was I sent one?',
  '9092': 'What is the Dropbox enterprise installer, and how can I use it to deploy Dropbox Business for my entire team?',
  '9093': 'Why can\'t I install a previous version of the Dropbox application?',
  '9094': 'Why is Dropbox saying it “stopped syncing because it can\'t update?”',
  '9095': 'How can I troubleshoot issues on the Dropbox website?',
  '9097': 'How do I save space on my computer?',
  '9098': 'How can I find out the email address for my Dropbox account?',
  '9099': 'How can I get more space?',
  '9100': 'Can I print an invoice?',
  '9102': 'Why did I get an email about photos I took on the weekend?',
  '9103': 'What is Flashback, and how do I use it?',
  '9104': 'How do I manually merge the contents of two Dropbox accounts?',
  '9107': 'How do I downgrade my Dropbox Pro subscription to a Basic account?',
  '9108': 'How do I cancel my Dropbox Business subscription?',
  '9109': 'What if I forgot my password or need to reset my password?',
  '9110': 'It looks like my file stopped syncing—what should I do?',
  '9112': 'How can Dropbox Business admins manage file requests for their team?',
  '9113': 'How can I stay protected from phishing and malware?',
  '9114': 'What\'s listed in version history?',
  '9115': 'Dropbox is syncing slowly—what factors external to Dropbox impact sync speed?',
  '9116': 'How do I migrate my data from a server to Dropbox?',
  '9117': 'Am I eligible for the Evernote + Dropbox space promotion?',
  '9118': 'Can I save a website URL in my Dropbox?',
  '9119': 'Who is the admin of my Dropbox Business team?',
  '9120': 'Am I eligible for the ASUS + Dropbox space promotion?',
  '9121': 'Dropbox for Salesforce: how do I add Dropbox to Publisher Layouts?',
  '9122': 'How can I quickly back up Office documents to my Dropbox?',
  '9123': 'How can I prevent Dropbox Business team members from permanently deleting files?',
  '9124': 'What is a team, and what can I do with this feature?',
  '9126': 'Something went wrong—what should I do?',
  '9127': 'Dropbox photos and videos are in the Gallery app on my Samsung device—how do I disable this?',
  '9128': 'Enabling and troubleshooting Dropbox for Gmail',
  '9129': 'What is the Dropbox Business Team page?',
  '9131': 'What is Dropbox Campus Cup, and how do I participate?',
  '9132': 'How do I get a link to a deletion event?',
  '9134': 'Why am I seeing consumption tax on my Dropbox subscription?',
  '9135': 'What is the Vodafone + Dropbox paid offer?',
  '9137': 'Why is Mailbox being shut down?',
  '9138': 'How should I prepare for the Mailbox shutdown?',
  '9139': 'What\'s a shared folder invite link, and how do I create one?',
  '9140': 'Why did I get an error message saying Dropbox is damaged?',
  '9141': 'What is "Continue as," and how do I use this feature?',
  '9142': 'My cancelled Dropbox Business subscription became a free team—why, and what does this mean?',
  '9143': 'What is a membership request, and how do I use one to join a team?',
  '9144': 'How do I turn on the Dropbox badge?',
  '9145': 'How does 3D Touch work in the Dropbox iOS app?',
  '9146': 'Why do I need to upgrade to OS X 10.6.8?',
  '9147': 'What are the various Vodafone + Dropbox promotions, and how much space can I earn?',
  '9148': 'What is the Telmex + Dropbox space promotion, and how do I know if I’m eligible?',
  '9149': 'Why won\'t my Selective Sync preferences update?',
  '9150': 'What is "Sign in as user," and how can I use it to manage accounts on my Dropbox Business team?',
  '9151': 'How does Dropbox Business integrate with Windows 10 Enterprise Data Protection?',
  '9152': 'Why did I receive a "Dropbox account unlinked" error message?',
  '9153': 'Dropbox Campus Cup: What if I linked my school address to someone else’s Dropbox account, or to an account I can no longer access?',
  '9154': 'How do I modify my Dropbox Paper account settings?',
  '9155': 'How do I use Dropbox Paper with two Dropbox accounts?',
  '9156': 'How can I migrate data from Hackpad to Dropbox Paper?',
  '9157': 'Do I have to have a Dropbox account to access a doc in Dropbox Paper?',
  '9158': 'What is the Dropbox Paper Following page, and how do I follow or unfollow a doc or folder?',
  '9159': 'How do I favorite a Dropbox Paper doc or folder?',
  '9160': 'What if there\'s an error creating the Dropbox folder in a new location?',
  '9161': 'Why couldn\'t the Dropbox folder be created in a new location?',
  '9162': 'What are Dropbox Paper folders, and how do I create or add to them?',
  '9163': 'How do I modify or delete a Dropbox Paper folder?',
  '9164': 'How do I create a new Dropbox Paper doc?',
  '9165': 'How do I track or restore changes or resolved comments on a Dropbox Paper doc?',
  '9166': 'How do I delete or restore a Dropbox Paper doc?',
  '9167': 'Adding media to Dropbox Paper: Images, video, and more.',
  '9168': 'How do I collaborate in a Dropbox Paper doc?',
  '9169': 'How do my Dropbox Paper docs integrate with Dropbox?',
  '9170': 'How do I find my Dropbox Paper docs?',
  '9171': 'How do I share a Dropbox Paper doc and adjust its permissions?',
  '9172': 'What are default share permissions for a Dropbox Paper doc?',
  '9173': 'What formatting options are available in Dropbox Paper?',
  '9174': 'How do I adjust my Dropbox Paper email notification settings?',
  '9175': 'What does it mean for a Dropbox product to be in "alpha" or "beta?"',
  '9176': 'What is the Adobe + Dropbox partnership?',
  '9177': 'Why does the Dropbox iOS app request access to my contacts?',
  '9178': 'How do I embed Google Docs, Sheets, and Slides in Dropbox Paper?',
  '9179': 'How do I suspend a team member\'s account on my Dropbox Business team?',
  '9180': 'What is custom branding, and how do I use it on shared links for my Dropbox Business team?',
  '9182': 'Why does Dropbox automatically update on my computer?',
  '9183': 'What are ".dropbox" files?',
  '9184': 'What is Dropbox Enterprise?',
  '9185': 'What is "Sign in as user," and how can I use it to manage accounts on my Dropbox Business team?',
  '9186': 'The admin on my Dropbox Business used "Sign in as user" to access my account—what does this mean?',
  '9187': 'How do I suspend a team member\'s account on my Dropbox Business team?',
  '9188': 'What is custom branding, and how do I use it on shared links for my Dropbox Business team?',
  '9189': 'Dropbox Business and HIPAA / HITECH—an overview.',
  '9190': 'Can I give Dropbox as a gift?',
  '9191': 'Am I eligible for the GoDaddy + Dropbox space promotion?',
  '9192': 'What Linux commands are available for Dropbox?',
  '9193': 'What are annotations, and how do they work?',
  '9194': 'How has shared link functionality changed?',
  '9197': 'What do I need to know about Carousel shutting down?',
  '9199': 'Why is Dropbox using more CPU than usual?'
};
